### ISSUE TITLE
Not able to impersonate chrome116

### ISSUE THREAD

**Issue by BhardwajAnshul** [lwthiker/curl-impersonate#198]
<curl_cffi.requests.models.Response object at 0x10445a210>
>>> session = requests.Session(impersonate='chrome116')
>>> session.get(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anshul/miniconda3/envs/main/lib/python3.11/site-packages/curl_cffi/requests/session.py", line 531, in request
    req, buffer, header_buffer = self._set_curl_options(
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anshul/miniconda3/envs/main/lib/python3.11/site-packages/curl_cffi/requests/session.py", line 346, in _set_curl_options
    raise RequestsError(f"impersonate {impersonate} is not supported")
curl_cffi.requests.errors.RequestsError: impersonate chrome116 is not supported

```
pip show curl_cffi
Name: curl-cffi
Version: 0.5.9
```

**Comment by lwthiker** [comment]
This has to do with the curl_cffi repository (https://github.com/yifeikong/curl_cffi) and not this one. Anyway, their most recent release supports chrome116.
