### ISSUE TITLE
./generate_dockerfiles.sh Shooot, could not parse view as JSON.

### ISSUE THREAD

**Issue by NabiKAZ** [lwthiker/curl-impersonate#32]
When I run `./generate_dockerfiles.sh` command, I get this error:

```
# ./generate_dockerfiles.sh
Shooot, could not parse view as JSON.
Tips: functions are not valid JSON and keys / values must be surround with double quotes.

SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseView (/usr/lib/node_modules/mustache/bin/mustache:74:17)
    at onDone (/usr/lib/node_modules/mustache/bin/mustache:67:10)
    at Socket.onEnd (/usr/lib/node_modules/mustache/bin/mustache:118:5)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Shooot, could not parse view as JSON.
Tips: functions are not valid JSON and keys / values must be surround with double quotes.
:
:
```

Content file:
```
# cat generate_dockerfiles.sh

#!/bin/sh
cat <<EOF | mustache - Dockerfile.template > chrome/Dockerfile
---
chrome: true
debian: true
---
EOF
:
:
```

Version:
```
# node -v
v10.24.1
# npm -v
6.14.12
# mustache -v
4.2.0
```

I could not resolve the problem, But I did it another way.

I created a file `config.json` with this content:
```
{
"chrome": true,
"debian": true
}
```

And then I ran this:
```
# cat config.json | mustache - Dockerfile.template > chrome/Dockerfile
```

It's works.

But you may want to fix that error above.

Thanks for your nice project.

**Comment by lwthiker** [comment]
Looks like you are using mustache.js which apparently doesn't support YAML. I'm running with the official ruby command line tool  from here: https://mustache.github.io/

btw, unless you modify `Dockerfile.template`, there's no need to run this script, the Dockerfiles in the repository are already up-to-date.
